# Generated by Django 2.2.16 on 2022-08-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Расскажите о себе', verbose_name='Биография'),
        ),
    ]
