# Generated by Django 2.2.16 on 2022-08-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220825_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
